version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    assignees:
      - "plaird"
    commit-message:
      prefix: "GitHub Actions update"
    open-pull-requests-limit: 2
