name: Build Everything

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Get Time for BUILD_ID
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: "YYYYMMDD_HHmm"

      - name: Get Branch name for BUILD_LABEL
        id: branch_name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Cache IntelliJ Aspects
        uses: actions/cache@v3
        with:
          path: ./bundles/com.salesforce.bazel.sdk/aspects
          key: ${{ runner.os }}-aspects-${{ hashFiles('**/aspects/import/import-and-build.sh', '**/aspects/import/WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-aspects

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      - name: Print Maven toolchains.xml
        run: cat ~/.m2/toolchains.xml

      - name: Import IntelliJ Aspects
        working-directory: ./bundles/com.salesforce.bazel.sdk/aspects/import
        shell: bash
        run: ./import-and-build.sh

      - name: Build and Test
        uses: coactions/setup-xvfb@v1
        env:
          BUILD_ID: "${{ steps.time.outputs.time }}"
          BUILD_TYPE: "S"
          BUILD_LABEL: "CI ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})"
        with:
          run: ./mvnw --batch-mode --no-transfer-progress --strict-checksums --fail-at-end -update-snapshots --show-version --errors clean verify
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          if-no-files-found: warn
          path: |
            ${{ github.workspace }}/**/target/surefire-reports/*.xml
